asset-transfer-basic/rest-api-typescript/.env.sample, asset-transfer-basic/rest-api-typescript/.eslintrc.json, asset-transfer-basic/rest-api-typescript/.gitignore, asset-transfer-basic/rest-api-typescript/.prettierrc.json, asset-transfer-basic/rest-api-typescript/README.md, asset-transfer-basic/rest-api-typescript/package-lock.json, asset-transfer-basic/rest-api-typescript/package.json, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/server.ts, asset-transfer-basic/rest-api-typescript/tsconfig.json
=> Initial REST API skeleton

asset-transfer-basic/rest-api-typescript/.env.sample, asset-transfer-basic/rest-api-typescript/package-lock.json, asset-transfer-basic/rest-api-typescript/package.json, asset-transfer-basic/rest-api-typescript/scripts/generateEnv.sh, asset-transfer-basic/rest-api-typescript/src/assets.router.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/logger.ts, asset-transfer-basic/rest-api-typescript/src/server.ts
=> Initial asset route

asset-transfer-basic/rest-api-typescript/.env.sample, asset-transfer-basic/rest-api-typescript/package-lock.json, asset-transfer-basic/rest-api-typescript/package.json, asset-transfer-basic/rest-api-typescript/scripts/generateEnv.sh, asset-transfer-basic/rest-api-typescript/src/assets.router.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/redis.ts, asset-transfer-basic/rest-api-typescript/src/server.ts
=> Initial create asset logic

README.md, asset-transfer-basic/rest-api-typescript/src/assets.router.ts
=> Add delete and put endpoints

README.md, asset-transfer-basic/rest-api-typescript/src/assets.router.ts
=> Add patch endpoint

README.md, asset-transfer-basic/rest-api-typescript/src/assets.router.ts
=> Add get all assets endpoint

demo.http
Add demo file for use with the REST Client for Visual Studio Code
=> Add REST Client demo file

.gitignore, asset-transfer-basic/rest-api-typescript/src/assets.router.ts, asset-transfer-basic/rest-api-typescript/src/errors.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/redis.ts
Remove duplication and handle errors from the asset transfer smart contract
=> Refactor transaction logic

asset-transfer-basic/rest-api-typescript/src/assets.router.ts, asset-transfer-basic/rest-api-typescript/src/errors.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/server.ts, asset-transfer-basic/rest-api-typescript/src/transactions.router.ts
=> Add get transaction endpoint

README.md, demo.http
Also adds new transactions endpoint example
=> Add Jira link to readme

asset-transfer-basic/rest-api-typescript/.env.sample, asset-transfer-basic/rest-api-typescript/scripts/generateEnv.sh, asset-transfer-basic/rest-api-typescript/src/assets.router.ts, asset-transfer-basic/rest-api-typescript/src/auth.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/server.ts, asset-transfer-basic/rest-api-typescript/src/transactions.router.ts
Signed-off-by: sapthasurendran <>
-  Gateway,network and contracts are switched based on  user api-key
=> Switch Fabric gateway based on user org

asset-transfer-basic/rest-api-typescript/jest.config.ts, asset-transfer-basic/rest-api-typescript/package-lock.json, asset-transfer-basic/rest-api-typescript/package.json, asset-transfer-basic/rest-api-typescript/src/__mocks__/config.ts, asset-transfer-basic/rest-api-typescript/src/__mocks__/fabric-network.ts, asset-transfer-basic/rest-api-typescript/src/__tests__/api.test.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/server.ts
=> Initial test framework

README.md, asset-transfer-basic/rest-api-typescript/.dockerignore, asset-transfer-basic/rest-api-typescript/Dockerfile, asset-transfer-basic/rest-api-typescript/docker-compose.yaml
Steps:
1)Build image from project directory
docker build -t fabricapp .
2) Generate .env file with env variables (use generateEnv.sh file or refer .env.sample)
3) Run docker-compose
docker-compose up
=> docker file for app

asset-transfer-basic/rest-api-typescript/src/config.ts
Discovered that env-var will validate port numbers, which is nice
=> Update port number config

asset-transfer-basic/rest-api-typescript/src/__mocks__/fabric-network.ts, asset-transfer-basic/rest-api-typescript/src/assets.router.ts, asset-transfer-basic/rest-api-typescript/src/auth.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/fabric.spec.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/server.ts, asset-transfer-basic/rest-api-typescript/src/transactions.router.ts
Attempt to make fabric code easier to document
=> Simplify fabric code

asset-transfer-basic/rest-api-typescript/src/health.router.ts, asset-transfer-basic/rest-api-typescript/src/server.ts
=> Refactor health routes in to separate file

asset-transfer-basic/rest-api-typescript/src/fabric.spec.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts
Signed-off-by: sapthasurendran <>
=> Clear Transaction when no contract found

asset-transfer-basic/rest-api-typescript/src/fabric.spec.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts
=> Fix lint errors

asset-transfer-basic/rest-api-typescript/src/config.spec.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/fabric.spec.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/server.ts
=> Add block event listener config

asset-transfer-basic/rest-api-typescript/src/fabric.ts
=> Add comments to fabric.ts

asset-transfer-basic/rest-api-typescript/src/errors.spec.ts, asset-transfer-basic/rest-api-typescript/src/errors.ts, asset-transfer-basic/rest-api-typescript/src/fabric.spec.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts
=> Move error related functions to errors.ts

asset-transfer-basic/rest-api-typescript/.env.sample, asset-transfer-basic/rest-api-typescript/README.md, asset-transfer-basic/rest-api-typescript/scripts/generateEnv.sh, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/index.ts
=> Signpost configuration details

asset-transfer-basic/rest-api-typescript/README.md, asset-transfer-basic/rest-api-typescript/src/config.spec.ts, asset-transfer-basic/rest-api-typescript/src/config.ts, asset-transfer-basic/rest-api-typescript/src/errors.spec.ts, asset-transfer-basic/rest-api-typescript/src/errors.ts, asset-transfer-basic/rest-api-typescript/src/fabric.spec.ts, asset-transfer-basic/rest-api-typescript/src/fabric.ts, asset-transfer-basic/rest-api-typescript/src/index.ts, asset-transfer-basic/rest-api-typescript/src/jobs.router.ts, asset-transfer-basic/rest-api-typescript/src/jobs.spec.ts, asset-transfer-basic/rest-api-typescript/src/jobs.ts, asset-transfer-basic/rest-api-typescript/src/redis.ts
Improve the separation between Fabric logic and the job queue implementation details
=> Clarify retry logic

asset-transfer-basic/rest-api-typescript/package-lock.json, asset-transfer-basic/rest-api-typescript/package.json
Match the versions required in asset-transfer-basic/application-typescript
Also update to latest version of fabric-network
=> Add node, and npm version requirements

asset-transfer-basic/rest-api-typescript/src/jobs.ts
=> Add comments to jobs.ts
